openapi: 3.0.0
info:
  version: 0.1.0
  title: ForgedFed Discovery Service
  description: 'This service is used to discover bridge interfaces that operate on forges. More information about this can be found on [GitHub](https://github.com/dat-adi/northstar)'
  license:
    name: AGPL3
    url: 'https://www.gnu.org/licenses/agpl-3.0-standalone.html'
  contact:
    name: ForgedFed Developers
    email: forgedfed@gmail.com
servers:
  - url: 'http://example.com'
tags:
  - name: interface
    description: A bridge component that talks the bridge protocol and is able to affect changes to the forge that it manages.
    externalDocs:
      description: Find out more about interfaces
      url: 'https://github.com/dat-adi/forgedfed-spec/blob/master/rfc/1-ecosystem-architecture/1-ecosystem-architecture.md'
paths:
  /api/v1/interface/register:
    post:
      tags:
        - interface
      summary: Add an interface to the discovery service
      description: |-
        A forge can have multiple interfaces. North Star is used to map relationships between a forge and the interfaces that operate on it, acting like a telephone direcory.
        This endpoint is used to register an interface against a forge in North Star
      operationId: registerInterface
      requestBody:
        description: Interface object that needs to be added to the discovery service
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                interface_url:
                  description: The publicly accessible URL of the bridge interface
                  type: string
                  example: 'https://forgedfed-interface.example.com'
                forge_url:
                  description: 'The publicly accessible URL of the forge that this interface manages. If a forge is known by more than one URL(separate bug tracker, and different fetch and push URLs for git), then mention them all in this field'
                  type: array
                  example:
                    - 'https://git.sr.ht/~sircmpwn/paste.sr.ht'
                    - 'git@git.sr.ht:~sircmpwn/paste.sr.ht'
                    - 'https://lists.sr.ht/~sircmpwn/sr.ht-discuss'
                  items:
                    type: string
                    example: 'https://git.sr.ht/~sircmpwn/paste.sr.ht'
      responses:
        '200':
          description: Successful registration
        '400':
          description: 'Registration failure, the forge list submitted is empty. An interface should handle at least one forge.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  errcode:
                    description: THE F_D_EMPTY_FORGE_LIST error code
                    type: string
                    example: F_D_EMPTY_FORGE_LIST
                  error:
                    description: A human-readable error message
                    type: string
                    example: The forge list submited is empty. An interface should handle at  least one forge.
        '503':
          description: 'Registration failure, interface couldn''t be reached via the URL provided'
          content:
            application/json:
              schema:
                type: object
                properties:
                  errcode:
                    description: The F_D_INTERFACE_UNREACHABLE error code
                    type: string
                    example: F_D_INTERFACE_UNREACHABLE
                  error:
                    description: A human-readable error message
                    type: string
                    example: The interface was unreachable with the publicly accessible URL provided
  /api/v1/forge/interfaces:
    post:
      tags:
        - interface
      summary: Get all interfaces registered against a forge
      description: 'To setup a bridge, an interface that can talk to the target forge must be identified. North Star is a lookup service that makes this possible. This endpoint is used to get all interfaces registered the queried forge'
      operationId: getInterfaces
      requestBody:
        description: Forge URL
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                forge_url:
                  description: The publicly accessible URL of the bridge interface
                  type: string
                  example: 'https://github.com'
      responses:
        '200':
          description: Query is successful and interfaces were found for the queried forge
          content:
            application/json:
              schema:
                type: object
                properties:
                  interfaces:
                    description: A list of interfaces registered against queried forge
                    type: array
                    example:
                      - 'https://interface1.example.com'
                      - 'https://interface2.example.com'
                      - 'https://interface3.example.com'
                    items:
                      type: string
                      example: 'https://interface3.example.com'
        '400':
          description: There are no interfaces registered against the queried forge
          content:
            application/json:
              schema:
                type: object
                properties:
                  errcode:
                    description: The F_D_NO_REGISTERED_INTERFACES error code
                    type: string
                    example: F_D_NO_REGISTERED_INTERFACES
                  error:
                    description: A human-readable error message
                    type: string
                    example: No interfaces are registered against the queried forge
        '500':
          description: Opration failure due to internal errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errcode:
                    description: The F_D_INTERNAL_SERVER_ERROR error code
                    type: string
                    example: F_D_INTERNAL_SERVER_ERROR
                  error:
                    description: A human-readable error message
                    type: string
                    example: 'Operation couldn''t be performed due to internal errors. If error persists, please contact admins.'
